### ISSUE TITLE
install

### ISSUE THREAD

**Issue by wanlilu** [AgastyaPatel/USD_Megascan_Importer#1]
how can i install the plugin??

**Comment by AgastyaPatel** [comment]
I'll address the issue by creating a guide. Please by weekend.

**Comment by AgastyaPatel** [comment]
Just updated the repo:
[Docs](https://agastyapatel.github.io/USD_Megascan_Importer/) Updated:)
[Releases](https://github.com/AgastyaPatel/USD_Megascan_Importer/releases) Just pushed a new release
Kindly check it out. Sorry for being extremely late for this update...I had to go through surgery due to accident after which most of my time was spent in PT. 
Anyways. Let me know if there's any suggestion with new issue:)
